routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@redirectAdmin')->name('index');
Route::get('/home', 'HomeController@index')->name('home');

/**
 * Admin routes
 */
Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'Backend\DashboardController@index')->name('admin.dashboard');
    Route::resource('roles', 'Backend\RolesController', ['names' => 'admin.roles']);
    Route::resource('users', 'Backend\UsersController', ['names' => 'admin.users']);
    Route::resource('admins', 'Backend\AdminsController', ['names' => 'admin.admins']);

    // compro
    Route::resource('company-profile', 'Backend\CompanyController', ['names' => 'config.company']);

    //mobil
    Route::resource('master-mobil', "Backend\MobilController", ["names" => "admin.master.mobil"]);
    Route::put('/delete/mobil/{id}', 'Backend\MobilController@delete')->name('admin.softDelete.mobil');
    Route::put('/restore/mobil/{id}', 'Backend\MobilController@restore')->name('admin.restore.mobil');

    // permisions
    Route::resource('config/permisions','Backend\PermissionsController', ['names' => 'admin.permisions']);
    Route::post('permissions/import', 'Backend\PermissionsController@importData')->name('admin.permisions.file-import');

    // Login Routes
    Route::get('/login', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::get('/register', 'Backend\Auth\LoginController@showRegisterForm')->name('admin.register');
    Route::post('/login/submit', 'Backend\Auth\LoginController@login')->name('admin.login.submit');
    Route::post('/admin/register', 'Backend\Auth\LoginController@register')->name('admin.register.submit');

    // Logout Routes
    Route::post('/logout/submit', 'Backend\Auth\LoginController@logout')->name('admin.logout.submit');

    // Forget Password Routes
    Route::get('/password/reset', 'Backend\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset/submit', 'Backend\Auth\ForgotPasswordController@reset')->name('admin.password.update');
});

app/Models/Mobil.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
class Mobil extends Model
{
    use Notifiable, HasRoles,HasFactory;
    protected $fillable = [
        'merek',
        'model',
        'plat_nomor',
        'tarif',
        'status',
        'image',
        'created_by',
        'updated_by',
    ];
}

app/Http/Controllers/Backend/MobilController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;
use App\Models\Mobil;
use App\Helpers\CurrencyHelper;  // Import the helper

class MobilController extends Controller
{
    public $user;

    public function __construct()
    {
        $this->middleware(function ($request, $next) {
            $this->user = Auth::guard('admin')->user();
            return $next($request);
        });
    }

    public function index(Request $request)
    {
        if (is_null($this->user) || !$this->user->can('mobil.view')) {
            abort(403, 'Sorry !! You are Unauthorized to view any admin !');
        }

        $query = Mobil::orderBy('id', 'DESC');

        if ($this->user->is_admin != 1) {
            $query->where('created_by', $this->user->name);
        }

        foreach ($request->all() as $key => $value) {
            if (!is_null($value) && $key != '_token') {
                $query->where($key, $value);
            }
        }

        $mobil = $query->get();
        return view('backend.pages.mobil.index', compact('mobil'));
    }
    public function create()
    {
        if (is_null($this->user) || !$this->user->can('mobil.create')) {
            abort(403, 'Sorry !! You are Unauthorized to create any admin !');
        }
      
        return view('backend.pages.mobil.create');
    }
    public function store(Request $request)
    {
        if (is_null($this->user) || !$this->user->can('mobil.create')) {
            abort(403, 'Sorry !! You are Unauthorized to create any admin !');
        }
        $request->validate([
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'merek' => 'required|string|max:255',
            'model' => 'required|string|max:255',
            'plat_nomor' => 'required|string|max:255',
            'tarif' => 'required', // Validasi untuk angka desimal dengan maksimal 2 angka desimal
        ], [
            'image.required' => 'Gambar tidak boleh kosong!',
            'image.image' => 'File harus berupa gambar!',
            'image.mimes' => 'Gambar harus berformat: jpeg, png, jpg, gif, svg!',
            'image.max' => 'Ukuran gambar maksimal adalah 2MB!',
            'merek.required' => 'Merek tidak boleh kosong!',
            'model.required' => 'Model tidak boleh kosong!',
            'plat_nomor.required' => 'Plat nomor tidak boleh kosong!',
            'tarif.required' => 'Tarif tidak boleh kosong!',
        ]);
        DB::beginTransaction();

        try {
           
            // Proses penyimpanan gambar dan data lainnya
            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $imageName = time() . '.' . $image->getClientOriginalExtension();
                $image->move(public_path('storage/images'), $imageName);
        
                // Simpan data ke database
                $mobil= new Mobil();
                $mobil->image = $imageName;
                $mobil->merek = $request->merek;
                $mobil->model = $request->model;
                $mobil->plat_nomor = $request->plat_nomor;
                $mobil->tarif =  CurrencyHelper::convertCurrencyToDecimal($request->tarif);
                $mobil->created_by = $this->user->name;
                $mobil->save();
            }
            
            DB::commit();

            // Redirect ke halaman login dengan pesan sukses
            return redirect()->route('admin.master.mobil.edit',$mobil->getKey())->with('success', 'Data mobil successful save! You can now login.');
        } catch (\Exception $e) {
            DB::rollBack();

            // Handle the error (e.g., log it and/or show a user-friendly message)
            return redirect()->route('admin.master.mobil.create')->with('error', 'Data mobil failed save! Please try again.');
        }        
    }
    public function edit(int $id)
    {
        if (is_null($this->user) || !$this->user->can('mobil.edit')) {
            abort(403, 'Sorry !! You are Unauthorized to edit any admin !');
        }
        $mobil = Mobil::find($id);
      
        return view('backend.pages.mobil.edit', compact('mobil'));
    }

    public function destroy($id)
    {
        if (is_null($this->user) || !$this->user->can('mobil.delete')) {
            abort(403, 'Sorry !! You are Unauthorized to delete any admin !');
        }
        $mobil = Mobil::find($id);
        if (!is_null($mobil)) {
            $mobil->delete();
        }
        session()->flash('success', 'Mobil Berhasil di delete Permanen!!');
        return redirect()->route('admin.master.mobil.index');    
    }

    public function delete($id)
    {
        if (is_null($this->user) || !$this->user->can('mobil.move')) {
            abort(403, 'Sorry !! You are Unauthorized to move any admin !');
        }
        $mobil = Mobil::find($id);
        $mobil->status=0;
        $mobil->save();
        session()->flash('success', 'Data Mobil Telah Di non aktifkan !!');
        return redirect()->route('admin.master.mobil.index');  
    }

    public function restore($id)
    {
        if (is_null($this->user) || !$this->user->can('mobil.restore')) {
            abort(403, 'Sorry !! You are Unauthorized to restore any admin !');
        }
       
        $mobil = Mobil::find($id);
        $mobil->status=1;
        $mobil->save();


        session()->flash('success', 'Data Mobil Telah Activate !!');
        return redirect()->route('admin.master.mobil.index');
    }
}

resources/views/backend/pages/mobil/create.blade.php
@extends('backend.layouts.master')

@section('title')
Mobil - Admin Panel
@endsection

@section('styles')
<link href="{{ asset('public/css/select2.min.css') }}" rel="stylesheet" />

<style>
    .form-check-label {
        text-transform: capitalize;
    }
</style>
@endsection
@section('admin-content')
<!-- page title area start -->
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Mobil</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                    <li><a href="{{ route('admin.master.mobil.index') }}">Mobil Data</a></li>
                    <li><span>Add Mobil</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            @include('backend.layouts.partials.logout')
        </div>
    </div>
</div>
<!-- page title area end -->
<div class="main-content-inner">
    <div class="row">
        <!-- data table start -->
        <div class="col-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Create Mobil</h4>
                    @include('backend.layouts.partials.messages')
                    
                    <form action="{{ route('admin.master.mobil.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="form-row">
                            <div class="form-group col-md-4 col-sm-12">
                                <label for="merek">Merek <span class="text-danger">*</span></label>
                                <input type="text" id="merek" name="merek" class="form-control" placeholder="Merek Mobil" />
                            </div>
                            <div class="form-group col-md-4 col-sm-12">
                                <label for="model">Model <span class="text-danger">*</span></label>
                                <input type="text" id="model" name="model" class="form-control" placeholder="Model Mobil" />
                            </div>
                            <div class="form-group col-md-4 col-sm-12">
                                <label for="plat_nomor">Plat Nomor <span class="text-danger">*</span></label>
                                <input type="text" id="plat_nomor" name="plat_nomor" class="form-control" placeholder="plat_nomor Mobil" />
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6 col-sm-12">
                                <label for="tarif">Tarif <span class="text-danger">*</span></label>
                                <input type="text" id="tarif" name="tarif" class="form-control" placeholder="Masukan Angka Rupiah" />
                            </div>
                            <div class="form-group col-md-6 col-sm-12">
                                <label>Gambar Mobil<span class="text-danger"> | jpeg,png,jpg,gif,svg|max:2MB</span></label>
                                <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" accept="image/*">
                                @error('image')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>                            
                        </div>
                        
                        <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4" style="border-radius: 10px;"><i class="fa fa-save"></i>  Save</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- data table end -->
        
    </div>
</div>
@endsection
@section('scripts')
<script>
    // Define function to format Rupiah currency
    function formatRupiah(angka) {
        var number_string = angka.toString().replace(/[^,\d]/g, ''),
            split = number_string.split(','),
            sisa = split[0].length % 3,
            rupiah = split[0].substr(0, sisa),
            ribuan = split[0].substr(sisa).match(/\d{3}/gi);
        
        if (ribuan) {
            separator = sisa ? '.' : '';
            rupiah += separator + ribuan.join('.');
        }
        
        rupiah = split[1] != undefined ? rupiah + ',' + split[1] : rupiah;
        return 'Rp ' + rupiah;
    }

    // Define event listener for input field
    document.getElementById('tarif').addEventListener('keyup', function() {
        // Get input value
        var inputValue = this.value;

        // Format input value as Rupiah currency
        var formattedValue = formatRupiah(inputValue);

        // Set formatted value back to input field
        this.value = formattedValue;
    });
</script>

    <script>

        $(document).ready(function () {
            $('.selectpicker').selectpicker();    
        });
    </script>
@endsection

resources/views/backend/pages/mobil/index.blade.php
@extends('backend.layouts.master')

@section('title')
Mobil - Panel
@endsection

@section('styles')
    <!-- Start datatable css -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.jqueryui.min.css">
@endsection
@section('admin-content')
{{-- breadcump --}}
<!-- page title area start -->
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Mobil</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                    <li><span>Mobil Data</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            @include('backend.layouts.partials.logout')
        </div>
    </div>
</div>
<!-- page title area end -->
<div class="main-content-inner">
    <div class="row">
        <!-- data table start -->
        <div class="col-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title float-left">Mobil Data</h4>
                    <p class="float-right mb-2">
                        <a class="btn btn-primary text-white" href="{{ route('admin.master.mobil.create') }}" style="border-radius: 15px;"> <i class="fa fa-plus"></i> Add Mobil</a>
                    </p>
                    
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="select-statuse">Status Data</label>
                                <select class="form-control selectpicker" data-live-search="true" name="status" id="select-status" onchange="push_to_url({status: this.value})">
                                    <option selected disabled>Choose Status Data</option>
                                    <option value="">View All</option>
                                    <option value="1">Active</option>
                                    <option value="0">Deactive</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="data-tables">
                        @include('backend.layouts.partials.messages')
                        <table id="dataTable" class="text-center w-100">
                            <thead class="bg-light text-capitalize">
                                <tr>
                                    <th width="5%">No</th>
                                    <th width="10%">Merek</th>
                                    <th width="10%">Model</th>
                                    <th width="10%">Plat Nomor</th>
                                    <th width="10%">Tarif</th>
                                    <th width="10%">status</th>
                                    <th width="10%">Created By</th>
                                    <th width="10%">Updated By</th>
                                    <th width="15%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               @foreach ($mobil as $mobil)
                               
                               <tr>
                                    <td>{{ $loop->index+1 }}</td>
                                    <td>{{ $mobil->merek }}</td>
                                    <td>{{ $mobil->model }}</td>
                                    <td>{{ $mobil->plat_nomor}}</td>
                                    <td>{{ $mobil->tarif }}</td>
                                    
                                    <td>
                                        @if ($mobil->status == 1)
                                            <i class="fa fa-circle text-success font-xs mr-1"></i>
                                            Active
                                        @else
                                            <i class="fa fa-circle text-danger font-xs mr-1"></i>
                                            Deactive
                                        @endif
                                    </td> 
                                    <td>{{ $mobil->created_by }}</td>
                                    <td>{{ $mobil->updated_by }}</td>
                                    <td>
                                        <div class="dropdown-container" style="font-size: 0.5rem;border-radius: 10px;">
                                            <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle"
                                                href="#" role="button" data-toggle="dropdown">
                                                <svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16 16" width="16" size="16" height="16" style="font-size:25px;" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5">
                                                    <circle cx="8" cy="2.5" r=".75"/>
                                                    <circle cx="8" cy="8" r=".75"/>
                                                    <circle cx="8" cy="13.5" r=".75"/>
                                                </svg>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list" style="border-radius: 15px;">
                                                <a class="dropdown-item"
                                                    href="{{ route('admin.master.mobil.show', $mobil->id) }}"><i class="fa fa-eye"></i> Show
                                                </a>

                                                <a class="dropdown-item"
                                                    href="{{ route('admin.master.mobil.edit', $mobil->id) }}"><i class="fa fa-pencil"></i> Edit
                                                </a>
                                                
                                                @if ($mobil->statuse==1)
                                                    <form method="POST" id="put-form-{{ $mobil->id }}" action="{{ route('admin.softDelete.mobil', $mobil->id) }}">
                                                        @csrf
                                                        <input name="_method" type="hidden" value="PUT">
                                                        <a type="submit" class="dropdown-item show_confirmdeac"  style="cursor:pointer" data-toggle="tooltip" title='Deactivate'><i class="fa fa-trash"></i> Deactivate</a>
                                                    </form>
                                                @endif
                                                @if ($mobil->statuse==0)
                                                    <form method="POST" id="put-form-{{ $mobil->id }}" action="{{ route('admin.restore.mobil', $mobil->id) }}">
                                                        @csrf
                                                        <input name="_method" type="hidden" value="PUT">
                                                        <a type="submit" class="dropdown-item restore"  style="cursor:pointer" data-toggle="tooltip" title='Restore Data'><i class="fa fa-undo"></i> Restore Data</a>
                                                    </form>
                                                @endif
                                                @if (Auth::guard('admin')->user()->entId == 1)
                                                    <form method="POST" id="delete-form-{{ $mobil->id }}" action="{{ route('admin.master.mobil.destroy', $mobil->id) }}">
                                                        @csrf
                                                        <input name="_method" type="hidden" value="DELETE">
                                                        <a type="submit" class="dropdown-item show_confirm" style="cursor:pointer" data-toggle="tooltip" title='Delete'><i class="fa fa-trash"></i> Delete</a>
                                                    </form>
                                                @endif
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                               @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- data table end -->
        
    </div>
</div>
@endsection
@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
    <script type="text/javascript">
        $('.show_confirmdeac').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Are you sure you want to delete this record?`,
                text: "If you delete this, data will be to deactivate.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                form.submit();
                }
            });
        });
        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Are you sure you want to delete this record?`,
                text: "If you delete this, it will be gone forever.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                form.submit();
                }
            });
        });
        $('.restore').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Are you sure you want to restore this record?`,
                text: "If you restore this, data will be usable again.",
                icon: "info",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                form.submit();
                }
            });
        });
    </script>
     <!-- Start datatable js -->
     <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
     <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
     <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
     <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
     <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js"></script>
     <script type="text/javascript">
        function push_to_url(params){
            const current_url = window.location.href;
            var urlParams = new URLSearchParams(window.location.search);

            if(Array.from(urlParams).some(([key, value]) => key === Object.keys(params)[0])){
                urlParams.set(Object.keys(params)[0], params[Object.keys(params)[0]])
                var newurl = window.location.origin + window.location.pathname + "?" + urlParams.toString();
            }else{
                var serializeparams = $.param(params);
                var sparactor = current_url.includes('?') ? '&' : '?';
                var newurl = current_url + sparactor + serializeparams;
            }

            window.location.href = newurl;
        }
     </script>
    <script>
        
        $(document).ready(function () {
            // $('.selectpicker').selectpicker();   

            $('#dataTable').DataTable({
                fixedHeader: true,
                fixedRows: true,
                responsive: false,
                pageLength : 10,

                scrollCollapse: true,
                scrollX: 400,
                fixedColumns: {
                    leftColumns: 1 // Tetapkan jumlah kolom yang ingin ditetapkan di sebelah kiri
                }

            });

            $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
                $($.fn.dataTable.tables(true)).DataTable()
                .columns.adjust()
                .responsive.recalc();
            });    
        });
     </script>
     
@endsection