routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@redirectAdmin')->name('index');
Route::get('/home', 'HomeController@index')->name('home');

/**
 * Admin routes
 */
Route::group(['prefix' => 'admin'], function () {
    Route::get('/', 'Backend\DashboardController@index')->name('admin.dashboard');
    Route::resource('roles', 'Backend\RolesController', ['names' => 'admin.roles']);
    Route::resource('users', 'Backend\UsersController', ['names' => 'admin.users']);
    Route::resource('admins', 'Backend\AdminsController', ['names' => 'admin.admins']);

    // compro
    Route::resource('company-profile', 'Backend\CompanyController', ['names' => 'config.company']);

    //mobil
    Route::resource('master-mobil', "Backend\MobilController", ["names" => "admin.master.mobil"]);
    Route::put('/delete/mobil/{id}', 'Backend\MobilController@delete')->name('admin.softDelete.mobil');
    Route::put('/restore/mobil/{id}', 'Backend\MobilController@restore')->name('admin.restore.mobil');

    // permisions
    Route::resource('config/permisions','Backend\PermissionsController', ['names' => 'admin.permisions']);
    Route::post('permissions/import', 'Backend\PermissionsController@importData')->name('admin.permisions.file-import');

    // Login Routes
    Route::get('/login', 'Backend\Auth\LoginController@showLoginForm')->name('admin.login');
    Route::get('/register', 'Backend\Auth\LoginController@showRegisterForm')->name('admin.register');
    Route::post('/login/submit', 'Backend\Auth\LoginController@login')->name('admin.login.submit');
    Route::post('/admin/register', 'Backend\Auth\LoginController@register')->name('admin.register.submit');

    // Logout Routes
    Route::post('/logout/submit', 'Backend\Auth\LoginController@logout')->name('admin.logout.submit');

    // Forget Password Routes
    Route::get('/password/reset', 'Backend\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
    Route::post('/password/reset/submit', 'Backend\Auth\ForgotPasswordController@reset')->name('admin.password.update');
});

resources/views/backend/pages/permisions/create.blade.php
@extends('backend.layouts.master')

@section('title')
Permissions Create - Admin Panel
@endsection

@section('styles')
<link href="{{ asset('public/css/select2.min.css') }}" rel="stylesheet" />

<style>
    .form-check-label {
        text-transform: capitalize;
    }
</style>
@endsection
@section('admin-content')
<!-- page title area start -->
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Permissions Create</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                    <li><a href="{{ route('admin.permisions.index') }}">All Permissions</a></li>
                    <li><span>Add Permissions</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            @include('backend.layouts.partials.logout')
        </div>
    </div>
</div>
<!-- page title area end -->
<div class="main-content-inner">
    <div class="row">
        <!-- data table start -->
        <div class="col-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Create Permissions</h4>
                    @include('backend.layouts.partials.messages')
                    <form action="{{ route('admin.permisions.store') }}" method="POST">
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-12 col-sm-12">
                                <label for="name">Permissions Name</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Permissions Name">
                            </div>
                          
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12 col-sm-12">
                                <label for="guard_name">Guard Name</label>
                                <input type="text" class="form-control" id="guard_name" name="guard_name" placeholder="Guard Name">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12 col-sm-12">
                                <label for="group_name">Group Name</label>
                                <input type="text" class="form-control" id="group_name" name="group_name" placeholder="Group Name">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Save Permissions</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- data table end -->
        
    </div>
</div>
@endsection

resources/views/backend/pages/permisions/edit.blade.php
@extends('backend.layouts.master')

@section('title')
Permissions Edit - Admin Panel
@endsection

@section('styles')
<link href="{{ asset('public/css/select2.min.css') }}" rel="stylesheet" />

<style>
    .form-check-label {
        text-transform: capitalize;
    }
</style>
@endsection
@section('admin-content')
<!-- page title area start -->
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Permissions Edit</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                    <li><a href="{{ route('admin.permisions.index') }}">All Permissions</a></li>
                    <li><span>Edit Permissions - {{ $permisions->name }}</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            @include('backend.layouts.partials.logout')
        </div>
    </div>
</div>
<!-- page title area end -->
<div class="main-content-inner">
    <div class="row">
        <!-- data table start -->
        <div class="col-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Edit Permissions - {{ $permisions->name }}</h4>
                    @include('backend.layouts.partials.messages')
                    
                    <form action="{{ route('admin.permisions.update', $permisions->id) }}" method="POST">
                        @method('PUT')
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-12 col-sm-12">
                                <label for="name">Permissions Name</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Permissions Name" value="{{ $permisions->name }}">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12 col-sm-12">
                                <label for="guard_name">Guard Name</label>
                                <input type="text" class="form-control" id="guard_name" name="guard_name" placeholder="guard_name" value="{{ $permisions->guard_name }}">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12 col-sm-12">
                                <label for="group_name">Group Name</label>
                                <input type="text" class="form-control" id="group_name" name="group_name" placeholder="group_name" value="{{ $permisions->group_name }}">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary mt-4 pr-4 pl-4">Updated Permissions</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- data table end -->
        
    </div>
</div>
@endsection

resources/views/backend/pages/permisions/index.blade.php
@extends('backend.layouts.master')

@section('title')
Permissions - Admin Panel
@endsection

@section('styles')
    <!-- Start datatable css -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.jqueryui.min.css">
@endsection
@section('admin-content')
{{-- breadcump --}}
<!-- page title area start -->
<div class="page-title-area">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <div class="breadcrumbs-area clearfix">
                <h4 class="page-title pull-left">Permissions</h4>
                <ul class="breadcrumbs pull-left">
                    <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
                    <li><span>Permissions Data</span></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6 clearfix">
            @include('backend.layouts.partials.logout')
        </div>
    </div>
</div>
<!-- page title area end -->
<div class="main-content-inner">
    <div class="row">
        <!-- data table start -->
        <div class="col-12 mt-5">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('admin.permisions.file-import') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <fieldset>
                            <h4>Import Permissions Data</h4>
                            <small class="warning text-muted">{{__('Please upload only Excel (.xlsx or .xls) files')}}</small>
                            <div class="input-group">
                                <input type="file" required class="form-control" name="uploaded_file" id="uploaded_file">
                                @if ($errors->has('uploaded_file'))
                                    <p class="text-right mb-0">
                                        <small class="danger text-muted" id="file-error">{{ $errors->first('uploaded_file') }}</small>
                                    </p>
                                @endif
                                <div class="input-group-append" id="button-addon2">
                                    <button class="btn btn-primary square" type="submit"><i class="ft-upload mr-1"></i> Import data</button>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title float-left">Permissions Data</h4>
                    <p class="float-right mb-2">
                        <a class="btn btn-primary text-white" href="{{ route('admin.permisions.create') }}">Add New Permissions</a>
                    </p>
                    
                    <div class="clearfix"></div>
                    <div class="data-tables">
                        @include('backend.layouts.partials.messages')
                        <table id="dataTable" class="text-center">
                            <thead class="bg-light text-capitalize">
                                <tr>
                                    <th width="5%">No</th>
                                    <th width="10%">Permissions Name</th>
                                    <th width="10%">Guard Name</th>
                                    <th width="10%">Group Name</th>
                                    <th width="10%">Created By</th>
                                    <th width="10%">Updated By</th>
                                    <th width="15%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               @foreach ($permisions as $permisions)
                               <tr>
                                    <td>{{ $loop->index+1 }}</td>
                                    <td>{{ $permisions->name }}</td>
                                    <td>{{ $permisions->guard_name }}</td>
                                    <td>{{ $permisions->group_name }}</td>
                                    <td>{{ $permisions->created_at }}</td>
                                    <td>{{ $permisions->updated_at }}</td>
                                    <td>
                                        <div class="dropdown-container" style="font-size: 0.5rem;border-radius: 10px;">
                                            <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle"
                                                href="#" role="button" data-toggle="dropdown">
                                                <svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 16 16" width="16" size="16" height="16" style="font-size:25px;" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5">
                                                    <circle cx="8" cy="2.5" r=".75"/>
                                                    <circle cx="8" cy="8" r=".75"/>
                                                    <circle cx="8" cy="13.5" r=".75"/>
                                                </svg>
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list" style="border-radius: 15px;">
                                                <a class="dropdown-item"
                                                    href="{{ route('admin.permisions.edit', $permisions->id) }}"><i class="fa fa-pencil"></i> Edit
                                                </a>
                                                <form method="POST" id="delete-form-{{ $permisions->id }}" action="{{ route('admin.permisions.destroy', $permisions->id) }}">
                                                    @csrf
                                                    <input name="_method" type="hidden" value="DELETE">
                                                    <a type="submit" class="dropdown-item show_confirm" style="cursor:pointer" data-toggle="tooltip" title='Delete'><i class="fa fa-trash"></i> Delete</a>
                                                </form>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                               @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- data table end -->
        
    </div>
</div>
@endsection
@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
    <script type="text/javascript">
        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Are you sure you want to delete this record?`,
                text: "If you delete this, it will be gone forever.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                form.submit();
                }
            });
        });
    </script>
     <!-- Start datatable js -->
     <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
     <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
     <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
     <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
     <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap.min.js"></script>
     
     <script>
         /*================================
        datatable active
        ==================================*/
        if ($('#dataTable').length) {
            $('#dataTable').DataTable({
                fixedHeader: true,
                fixedRows: true,
                responsive: false,
            });
        }

     </script>
@endsection